/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CtlHabitacion;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import modelo.Habitacion;

/**
 *
 * @author Jopcion
 */
public class AlquilarHabitacionVista extends javax.swing.JInternalFrame implements MouseListener {

    /**
     * Creates new form AlquilarHabitacionVista
     */
    CtlHabitacion controlHabitacion;
    private List<JLabel> labels;
    private List<Habitacion> habitaciones;
    private int cedula;
    private boolean huesped;

    public AlquilarHabitacionVista() {
        initComponents();
        setVisible(true);
        setMaximizable(false);
        setIconifiable(true);
        setClosable(true);
        setResizable(true);
        this.setTitle("ALQUILAR HABITACION");
        controlHabitacion = new CtlHabitacion();
        mostrarHabitaciones();
    }

    public AlquilarHabitacionVista(int cedula) {
        initComponents();
        setVisible(true);
        setMaximizable(false);
        setIconifiable(true);
        setClosable(true);
        setResizable(true);
        this.setTitle("ALQUILAR HABITACION");
        controlHabitacion = new CtlHabitacion();
        mostrarHabitaciones();
        this.cedula = cedula;
    }

    public AlquilarHabitacionVista(int cedula, boolean huesped) {
        initComponents();
        setVisible(true);
        setMaximizable(false);
        setIconifiable(true);
        setClosable(true);
        setResizable(true);
        this.setTitle("ALQUILAR HABITACION");
        controlHabitacion = new CtlHabitacion();
        mostrarHabitaciones();
        this.cedula = cedula;
        this.huesped = huesped;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contenedorJLabel = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/key.png"))); // NOI18N
        jLabel2.setText("                       HABITACION");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 510, 80));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 90));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("HABITACIONES DISPONIBLES:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        contenedorJLabel.setLayout(new java.awt.GridLayout(0, 3));
        jScrollPane1.setViewportView(contenedorJLabel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 700, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 720, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlquilarHabitacionVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlquilarHabitacionVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlquilarHabitacionVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlquilarHabitacionVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlquilarHabitacionVista().setVisible(true);
            }
        });
    }

    public void mostrarHabitaciones() {
        labels = new ArrayList();
        habitaciones = controlHabitacion.listarHabitaciones();
        for (int i = 0; i < habitaciones.size(); i++) {
            JLabel l;
            try {
                byte[] bi = habitaciones.get(i).getFoto();
                BufferedImage imagen = null;
                InputStream in = new ByteArrayInputStream(bi);
                imagen = ImageIO.read(in);
                ImageIcon imgi = new ImageIcon(imagen.getScaledInstance(180, 180, 180));
                l = new JLabel(imgi);

            } catch (Exception e) {
                l = new JLabel(habitaciones.get(i).getIdHabitacion() + "");
            }
            l.setName(habitaciones.get(i).getIdHabitacion() + "");
            l.addMouseListener(this);
            contenedorJLabel.add(l);
            labels.add(l);
            contenedorJLabel.updateUI();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorJLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        for (int i = 0; i < labels.size(); i++) {
            if (labels.get(i) == e.getSource()) {
                DetalleHabitacionVista d = null;
                boolean o = false;
                if (huesped == false) {
                    String cedula = JOptionPane.showInputDialog("ingrese la cedula del huesped");
                    if (cedula.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "debe ingresar el valor de la cedula");
                        o = false;
                    } else {
                        d = new DetalleHabitacionVista(Integer.parseInt(labels.get(i).getName()), Integer.parseInt(cedula),huesped);
                        o = true;
                    }
                } else {
                    d = new DetalleHabitacionVista(Integer.parseInt(labels.get(i).getName()), cedula, huesped);
                    o = true;
                }

                if (o) {
                    PrincipalVista.PanelVista.remove(PrincipalVista.ventanaActual);
                    PrincipalVista.PanelVista.repaint();
                    PrincipalVista.ventanaActual = d;
                    PrincipalVista.PanelVista.add(PrincipalVista.ventanaActual);
                }

            }
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {

    }

    @Override
    public void mouseReleased(MouseEvent e) {

    }

    @Override
    public void mouseEntered(MouseEvent e) {

    }

    @Override
    public void mouseExited(MouseEvent e) {

    }
}
