/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CtlHuesped;
import controlador.CtlRecepcion;
import javax.swing.JOptionPane;
import modelo.Huesped;
import modelo.Recepcionista;

/**
 *
 * @author Jopcion
 */
public class Login extends javax.swing.JFrame {

    CtlRecepcion controlRecepcion;
    CtlHuesped controlHuesped;
    Huesped cliente;

    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("LOGIN");
        controlHuesped = new CtlHuesped();
        controlRecepcion = new CtlRecepcion();
        cliente = new Huesped();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jtxUser = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jtxPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblInforamcion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 70, 90));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Iniciar Sesión");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 170, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/newUser.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 40, 40));

        jtxUser.setBackground(new java.awt.Color(51, 70, 90));
        jtxUser.setForeground(new java.awt.Color(255, 255, 255));
        jtxUser.setBorder(null);
        jPanel2.add(jtxUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 170, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 170, 10));

        jtxPassword.setBackground(new java.awt.Color(51, 70, 90));
        jtxPassword.setForeground(new java.awt.Color(255, 255, 255));
        jtxPassword.setBorder(null);
        jPanel2.add(jtxPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 170, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/newPassword.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 40, 40));

        btnIngresar.setBackground(new java.awt.Color(51, 70, 90));
        btnIngresar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel2.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        btnRegistrar.setBackground(new java.awt.Color(51, 70, 90));
        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("USUARIO:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 60, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CONTRASEÑA:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        lblInforamcion.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(lblInforamcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 244, 210, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 0, 360, 340));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LoginHotel.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 150, 140));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("HOTEL J & J");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        LoginHuespedVista lh = new LoginHuespedVista();
        lh.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        String user = jtxUser.getText();
        String contrasenia = jtxPassword.getText();
        try {
            Huesped cli = controlHuesped.buscarHuespedLogin(user, contrasenia);
            Recepcionista ven = controlRecepcion.buscarRecepcionistaLogin(user);

            if (jtxUser.getText().isEmpty() || jtxPassword.getText().isEmpty()) {
                lblInforamcion.setText("debe llenar todos los campos");
                return;
            } else {
                if (user.equals("admin") && contrasenia.equals("123")) {
                    JOptionPane.showMessageDialog(null, "Bienvenido Al sistema del HotelJyJ: " + user);
                    PrincipalVista vistaAdmin = new PrincipalVista();
                    vistaAdmin.setVisible(true);
                    dispose();
                } else if (cli != null) {
                    if (cli.getCorreo().equals(user) && cli.getContrasenia().equals(contrasenia)) {
                        JOptionPane.showMessageDialog(null, "Bienvenido al HotelJyJ: " + user);
                        restringirBotonesHuesped(cli.getCedula());
                        dispose();
                    }
                } else if (ven != null) {
                    if (ven.getUsuario().equals(user) && ven.getContrasenia().equals(contrasenia)) {
                        JOptionPane.showMessageDialog(null, "Bienvenido a la Recepcion del HotelJyJ: " + user);
                        restringirBotonesRecepcion(ven.getCodigo());
                        restringirVentaRecepcion();
                        dispose();
                    }
                }
            }
        } catch (NullPointerException e) {
            lblInforamcion.setText("Usuario o contraseña incorrectos");
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField jtxPassword;
    private javax.swing.JTextField jtxUser;
    private javax.swing.JLabel lblInforamcion;
    // End of variables declaration//GEN-END:variables
 
    private void restringirBotonesHuesped(int id) {
        PrincipalVista vistaHuesped = new PrincipalVista(id, true);
        vistaHuesped.setVisible(true);
        vistaHuesped.btnHuesped.setVisible(false);
        vistaHuesped.btnRegistroPedido.setVisible(false);
        vistaHuesped.btnRecepcionista.setVisible(false);
        vistaHuesped.btnRegistroHabitacion.setVisible(false);
        vistaHuesped.btnCheckIn.setVisible(false);
        vistaHuesped.btnCheckOut.setVisible(false);
        vistaHuesped.btnCancelarMulta.setVisible(false);
        vistaHuesped.btnRegistroPedido.setVisible(false);
        vistaHuesped.btnFactura.setVisible(true);
        vistaHuesped.btnDetalle.setVisible(false);
        vistaHuesped.btnReserva.setVisible(false);
        vistaHuesped.btnHistorial.setVisible(false);
    }

    private void restringirBotonesRecepcion(int id) {
        PrincipalVista vistaRecepcion = new PrincipalVista(id, false);
        vistaRecepcion.setVisible(true);
        vistaRecepcion.btnRecepcionista.setVisible(false);
        vistaRecepcion.btnRegistroHabitacion.setVisible(false);
        vistaRecepcion.btnRegistroPedido.setVisible(false);
        vistaRecepcion.btnDetalle.setVisible(false);
        vistaRecepcion.btnFactura.setVisible(false);

        
    }

    public void restringirVentaRecepcion() {
        RegistroHuespedVista vistaHuespe = new RegistroHuespedVista();
        vistaHuespe.btnEditar.setEnabled(false);
        vistaHuespe.btnListar.setEnabled(false);
    }
}
