/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
//
//import repositorio.LoginVista;

import controlador.CtlConfirmarreserva;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import modelo.ConfirmarReserva;

/**
 *
 * @author MI PC
 */
public class PrincipalVista extends javax.swing.JFrame {

    public static JInternalFrame ventanaActual;

    /**
     * Creates new form FrmLogin
     */
    private int idUsuario;
    private CtlConfirmarreserva controlConfirmarReserva;
    private boolean huesped;

    public PrincipalVista() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("HOTEL");
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    public PrincipalVista(int idUsuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("HOTEL");
        this.idUsuario = idUsuario;
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    public PrincipalVista(int idUsuario, boolean huesped) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("HOTEL");
        this.setExtendedState(MAXIMIZED_BOTH);
        this.idUsuario = idUsuario;
        controlConfirmarReserva = new CtlConfirmarreserva();
        this.huesped = huesped;
        if (huesped) {
            List<ConfirmarReserva> lista = controlConfirmarReserva.listarConfirmarReservasActivasHuesped(idUsuario);
            System.out.println("cantidad :" + lista.size());
            if (lista.size() > 0) {
                btnServicios.setEnabled(true);
            } else {
                btnServicios.setEnabled(false);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnHuesped = new javax.swing.JButton();
        btnRegistroHabitacion = new javax.swing.JButton();
        btnRecepcionista = new javax.swing.JButton();
        btnRegistroPedido = new javax.swing.JButton();
        btnHabitacion = new javax.swing.JButton();
        btnDetalle = new javax.swing.JButton();
        btnCheckIn = new javax.swing.JButton();
        btnCheckOut = new javax.swing.JButton();
        btnCancelarMulta = new javax.swing.JButton();
        btnFactura = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        btnReserva = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        PanelVista = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBorder(null);
        jToolBar1.setRollover(true);
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnHuesped.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_customer_32px_1.png"))); // NOI18N
        btnHuesped.setText("Registro Huesped");
        btnHuesped.setFocusable(false);
        btnHuesped.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHuesped.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuespedActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHuesped);

        btnRegistroHabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/habitacionRegistro.png"))); // NOI18N
        btnRegistroHabitacion.setText("Registro Habitacion");
        btnRegistroHabitacion.setFocusable(false);
        btnRegistroHabitacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistroHabitacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistroHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroHabitacionActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRegistroHabitacion);

        btnRecepcionista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Recepcionista_1.jpg"))); // NOI18N
        btnRecepcionista.setText("Registro Recepcionista");
        btnRecepcionista.setFocusable(false);
        btnRecepcionista.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRecepcionista.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRecepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecepcionistaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRecepcionista);

        btnRegistroPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/food.png"))); // NOI18N
        btnRegistroPedido.setText("Registrar Pedido");
        btnRegistroPedido.setFocusable(false);
        btnRegistroPedido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistroPedido.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistroPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroPedidoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnRegistroPedido);

        btnHabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Habitacion1.jpg"))); // NOI18N
        btnHabitacion.setText("Habitacion");
        btnHabitacion.setFocusable(false);
        btnHabitacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHabitacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabitacionActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHabitacion);

        btnDetalle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lista_1.png"))); // NOI18N
        btnDetalle.setText("Detalle Habitacion");
        btnDetalle.setFocusable(false);
        btnDetalle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDetalle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalleActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDetalle);

        btnCheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/check-in.png"))); // NOI18N
        btnCheckIn.setText("Check-In");
        btnCheckIn.setFocusable(false);
        btnCheckIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCheckIn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCheckIn);

        btnCheckOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/check-out.png"))); // NOI18N
        btnCheckOut.setText("Check-Out");
        btnCheckOut.setFocusable(false);
        btnCheckOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCheckOut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCheckOut);

        btnCancelarMulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/payment.png"))); // NOI18N
        btnCancelarMulta.setText("Cancelar Multa");
        btnCancelarMulta.setFocusable(false);
        btnCancelarMulta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelarMulta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelarMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarMultaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCancelarMulta);

        btnFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Reserva.png"))); // NOI18N
        btnFactura.setText("MisReservas");
        btnFactura.setFocusable(false);
        btnFactura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFactura.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFactura);

        btnServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/HacerPedido.png"))); // NOI18N
        btnServicios.setText("Servicios");
        btnServicios.setFocusable(false);
        btnServicios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnServicios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServiciosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnServicios);

        btnReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Reserva.png"))); // NOI18N
        btnReserva.setText("Hacer Reserva");
        btnReserva.setFocusable(false);
        btnReserva.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReserva.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnReserva);

        btnHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/history.png"))); // NOI18N
        btnHistorial.setText("Historial");
        btnHistorial.setFocusable(false);
        btnHistorial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHistorial.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHistorial);

        PanelVista.setBackground(new java.awt.Color(204, 204, 204));
        PanelVista.setForeground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout PanelVistaLayout = new javax.swing.GroupLayout(PanelVista);
        PanelVista.setLayout(PanelVistaLayout);
        PanelVistaLayout.setHorizontalGroup(
            PanelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelVistaLayout.setVerticalGroup(
            PanelVistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );

        btnLogin.setBackground(new java.awt.Color(102, 102, 102));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelVista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1106, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogin)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnLogin)))
                .addGap(18, 18, 18)
                .addComponent(PanelVista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuespedActionPerformed
        if (ventanaActual == null) {
            ventanaActual = new RegistroHuespedVista();
            PanelVista.add(ventanaActual);
        } else {
            PanelVista.remove(ventanaActual);
            PanelVista.repaint();
            ventanaActual = new RegistroHuespedVista();
            PanelVista.add(ventanaActual);

        }
    }//GEN-LAST:event_btnHuespedActionPerformed

    private void btnRegistroHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroHabitacionActionPerformed
        if (ventanaActual == null) {
            ventanaActual = new RegistroHabitacionVista();
            PanelVista.add(ventanaActual);
        } else {
            PanelVista.remove(ventanaActual);
            PanelVista.repaint();
            ventanaActual = new RegistroHabitacionVista();
            PanelVista.add(ventanaActual);

        }
    }//GEN-LAST:event_btnRegistroHabitacionActionPerformed

    private void btnRecepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecepcionistaActionPerformed
        if (ventanaActual == null) {
            ventanaActual = new RegistroRecepcionistaVista();
            PanelVista.add(ventanaActual);
        } else {
            PanelVista.remove(ventanaActual);
            PanelVista.repaint();
            ventanaActual = new RegistroRecepcionistaVista();
            PanelVista.add(ventanaActual);

        }
    }//GEN-LAST:event_btnRecepcionistaActionPerformed

    private void btnRegistroPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroPedidoActionPerformed
        if (ventanaActual == null) {
            ventanaActual = new RegistroPedidoVista();
            PanelVista.add(ventanaActual);
        } else {
            PanelVista.remove(ventanaActual);
            PanelVista.repaint();
            ventanaActual = new RegistroPedidoVista();
            PanelVista.add(ventanaActual);
        }
    }//GEN-LAST:event_btnRegistroPedidoActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        //C:\Users\STIVEN\OneDrive\Documentos\Netbeans\HotelJyJ\src\imagenes
        ImageIcon icono = new ImageIcon("C:\\Users\\STIVEN\\OneDrive\\Documentos\\Netbeans\\HotelJyJ\\src\\imagenes\\salida.png");
        int seleccion = JOptionPane.showConfirmDialog(null, "Desea cerrar sesión", "¿Deseas Salir?",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE, icono);
        if (seleccion == 0) {
            Login lv = new Login();
            lv.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabitacionActionPerformed
        // TODO add your handling code here:
        if (ventanaActual == null) {
            ventanaActual = new AlquilarHabitacionVista(idUsuario, huesped);
            PanelVista.add(ventanaActual);
        } else {
            PanelVista.remove(ventanaActual);
            PanelVista.repaint();
            ventanaActual = new AlquilarHabitacionVista(idUsuario, huesped);
            PanelVista.add(ventanaActual);

        }
    }//GEN-LAST:event_btnHabitacionActionPerformed

    private void btnDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleActionPerformed
        // TODO add your handling code here:
        if (ventanaActual == null) {
            ventanaActual = new DetalleHabitacionVista();
            PanelVista.add(ventanaActual);
        } else {
            PanelVista.remove(ventanaActual);
            PanelVista.repaint();
            ventanaActual = new DetalleHabitacionVista();
            PanelVista.add(ventanaActual);

        }
    }//GEN-LAST:event_btnDetalleActionPerformed

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        // TODO add your handling code here:
        if (ventanaActual == null) {
            ventanaActual = new ActivarReservaVista(idUsuario);
            PanelVista.add(ventanaActual);
        } else {
            PanelVista.remove(ventanaActual);
            PanelVista.repaint();
            ventanaActual = new ActivarReservaVista(idUsuario);
            PanelVista.add(ventanaActual);

        }
    }//GEN-LAST:event_btnCheckInActionPerformed

    private void btnCancelarMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarMultaActionPerformed
        // TODO add your handling code here:
        if (ventanaActual == null) {
            ventanaActual = new CancelarMultaVista();
            PanelVista.add(ventanaActual);
        } else {
            PanelVista.remove(ventanaActual);
            PanelVista.repaint();
            ventanaActual = new CancelarMultaVista();
            PanelVista.add(ventanaActual);

        }
    }//GEN-LAST:event_btnCancelarMultaActionPerformed

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
        // TODO add your handling code here:
        if (ventanaActual == null) {
            ventanaActual = new ReservasDeHuespedVista();
            PanelVista.add(ventanaActual);
        } else {
            PanelVista.remove(ventanaActual);
            PanelVista.repaint();
            ventanaActual = new ReservasDeHuespedVista();
            PanelVista.add(ventanaActual);

        }

    }//GEN-LAST:event_btnFacturaActionPerformed

    private void btnServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServiciosActionPerformed
        // TODO add your handling code here:
        if (ventanaActual == null) {
            ventanaActual = new HacerPedidoVista(idUsuario);
            PanelVista.add(ventanaActual);
        } else {
            PanelVista.remove(ventanaActual);
            PanelVista.repaint();
            ventanaActual = new HacerPedidoVista(idUsuario);
            PanelVista.add(ventanaActual);

        }
    }//GEN-LAST:event_btnServiciosActionPerformed

    private void btnReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservaActionPerformed
        // TODO add your handling code here:
        if (ventanaActual == null) {
            ventanaActual = new HacerReservaVista();
            PanelVista.add(ventanaActual);
        } else {
            PanelVista.remove(ventanaActual);
            PanelVista.repaint();
            ventanaActual = new HacerReservaVista();
            PanelVista.add(ventanaActual);

        }
    }//GEN-LAST:event_btnReservaActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        // TODO add your handling code here:
        if (ventanaActual == null) {
            ventanaActual = new CheckOutVista();
            PanelVista.add(ventanaActual);
        } else {
            PanelVista.remove(ventanaActual);
            PanelVista.repaint();
            ventanaActual = new CheckOutVista();
            PanelVista.add(ventanaActual);

        }
    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        // TODO add your handling code here:
        if (ventanaActual == null) {
            ventanaActual = new HistorialVista();
            PanelVista.add(ventanaActual);
        } else {
            PanelVista.remove(ventanaActual);
            PanelVista.repaint();
            ventanaActual = new HistorialVista();
            PanelVista.add(ventanaActual);
        }
    }//GEN-LAST:event_btnHistorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalVista().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel PanelVista;
    public javax.swing.JButton btnCancelarMulta;
    public javax.swing.JButton btnCheckIn;
    public javax.swing.JButton btnCheckOut;
    public javax.swing.JButton btnDetalle;
    public javax.swing.JButton btnFactura;
    public javax.swing.JButton btnHabitacion;
    public javax.swing.JButton btnHistorial;
    public javax.swing.JButton btnHuesped;
    private javax.swing.JButton btnLogin;
    public javax.swing.JButton btnRecepcionista;
    public javax.swing.JButton btnRegistroHabitacion;
    public javax.swing.JButton btnRegistroPedido;
    public javax.swing.JButton btnReserva;
    public javax.swing.JButton btnServicios;
    public javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
