/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CtlHuesped;
import controlador.CtlRecepcion;
import excepciones.EmpleadoNoexistenteException;
import excepciones.PersonaExistenteException;
import excepciones.PersonaNoEncontradaException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.Huesped;
import modelo.Recepcionista;

/**
 *
 * @author Jopcion
 */
public class RegistroHuespedVista extends javax.swing.JInternalFrame {

    CtlHuesped controlHuesped;
    CtlRecepcion controlRecepcion;

    public RegistroHuespedVista() {
        initComponents();
        setVisible(true);
        setMaximizable(false);
        setIconifiable(true);
        setClosable(true);
        setResizable(true);
        this.setTitle("HUESPED");
        controlHuesped = new CtlHuesped();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpingreso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxNombre = new javax.swing.JTextField();
        jtxCedula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxApellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxCorreo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtxContrasenia = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHuesped = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpingreso.setBackground(new java.awt.Color(255, 255, 255));
        jpingreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jpingreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(238, 112, 82));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Cedula:");
        jpingreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setBackground(new java.awt.Color(238, 112, 82));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");
        jpingreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jtxNombre.setForeground(new java.awt.Color(51, 51, 51));
        jpingreso.add(jtxNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 142, 27));

        jtxCedula.setForeground(new java.awt.Color(51, 51, 51));
        jtxCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxCedulaActionPerformed(evt);
            }
        });
        jtxCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxCedulaKeyTyped(evt);
            }
        });
        jpingreso.add(jtxCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 30));

        jLabel5.setBackground(new java.awt.Color(238, 112, 82));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Apellido:");
        jpingreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jtxApellido.setForeground(new java.awt.Color(51, 51, 51));
        jpingreso.add(jtxApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 139, 27));

        jLabel7.setBackground(new java.awt.Color(238, 112, 82));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Telefono:");
        jpingreso.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jtxTelefono.setForeground(new java.awt.Color(51, 51, 51));
        jtxTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxTelefonoKeyTyped(evt);
            }
        });
        jpingreso.add(jtxTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 139, 30));

        jLabel8.setBackground(new java.awt.Color(238, 112, 82));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Dirección:");
        jpingreso.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jtxDireccion.setForeground(new java.awt.Color(51, 51, 51));
        jpingreso.add(jtxDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 139, 30));

        jLabel9.setBackground(new java.awt.Color(238, 112, 82));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Correo:");
        jpingreso.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jtxCorreo.setForeground(new java.awt.Color(51, 51, 51));
        jpingreso.add(jtxCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 139, 30));

        btnGuardar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnGuardar.setText("REGISTRAR");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jpingreso.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 120, -1));

        btnListar.setBackground(new java.awt.Color(255, 255, 255));
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Listar.jpg"))); // NOI18N
        btnListar.setBorderPainted(false);
        btnListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        jpingreso.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 90, 70));

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Search_32px.png"))); // NOI18N
        btnBuscar.setBorderPainted(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jpingreso.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 91, 70));

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Editar02.jpg"))); // NOI18N
        btnEditar.setBorderPainted(false);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jpingreso.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 90, 70));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña:");
        jpingreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));
        jpingreso.add(jtxContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 140, 30));

        getContentPane().add(jpingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 520));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 409, -1, -1));

        jTableHuesped.setBackground(new java.awt.Color(0, 255, 255));
        jTableHuesped.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jTableHuesped.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableHuesped.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTableHuesped);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 630, 520));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("REGISTRO HUESPED");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxCedulaActionPerformed

    private void jtxCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxCedulaKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtxCedulaKeyTyped

    private void jtxTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxTelefonoKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtxTelefonoKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here: 
        if (jtxCedula.getText().isEmpty() || jtxNombre.getText().isEmpty() || jtxApellido.getText().isEmpty() || jtxTelefono.getText().isEmpty()
                || jtxDireccion.getText().isEmpty() || jtxCorreo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Son requeridos los campos", "¡Aviso!", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            int codigo = Integer.parseInt(jtxCedula.getText());
            String nombre = jtxNombre.getText();
            String apellido = jtxApellido.getText();
            int telefono = Integer.parseInt(jtxTelefono.getText());
            String direccion = jtxDireccion.getText();
            String correo = jtxCorreo.getText();
            String contrasenia = jtxContrasenia.getText();
            try {
                Recepcionista recepcion = controlRecepcion.buscarRecepcionista(codigo);
                if (recepcion == null) {
                    Huesped huesped = new Huesped(codigo, nombre, apellido, telefono, direccion, correo, contrasenia);
                    controlHuesped.guardarHuesped(huesped);
                    JOptionPane.showMessageDialog(this, "Se hizo el registro correctamente " + nombre);
                    refrescar();
                }

            } catch (PersonaExistenteException | PersonaNoEncontradaException | EmpleadoNoexistenteException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        try {
            int cedula = Integer.parseInt(jtxCedula.getText());
            Huesped buscar = controlHuesped.buscarHuesped(cedula);
            if (cedula == buscar.getCedula()) {
                cargarDatos(buscar);
                jtxCedula.setEnabled(false);
            }
        } catch (PersonaNoEncontradaException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(jtxCedula.getText());
        String nombre = jtxNombre.getText();
        String apellido = jtxApellido.getText();
        int telefono = Integer.parseInt(jtxTelefono.getText());
        String direccion = jtxDireccion.getText();
        String correo = jtxCorreo.getText();
        String contrasenia = jtxContrasenia.getText();
                try {
            Huesped huesped = new Huesped(codigo, nombre, apellido, telefono, direccion, correo, contrasenia);
            controlHuesped.modificarHuesped(huesped);
            JOptionPane.showMessageDialog(this, "Se hizo el registro correctamente " + nombre);
            refrescar();
            jtxCedula.setEnabled(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        listarHuesped();
    }//GEN-LAST:event_btnListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroHuespedVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroHuespedVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroHuespedVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroHuespedVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroHuespedVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHuesped;
    public javax.swing.JPanel jpingreso;
    private javax.swing.JTextField jtxApellido;
    private javax.swing.JTextField jtxCedula;
    private javax.swing.JPasswordField jtxContrasenia;
    private javax.swing.JTextField jtxCorreo;
    private javax.swing.JTextField jtxDireccion;
    private javax.swing.JTextField jtxNombre;
    private javax.swing.JTextField jtxTelefono;
    // End of variables declaration//GEN-END:variables
    private void refrescar() {
        jtxApellido.setText("");
        jtxCedula.setText("");
        jtxDireccion.setText("");
        jtxNombre.setText("");
        jtxTelefono.setText("");
        jtxCorreo.setText("");
    }

    private void cargarDatos(Huesped huesped) {
        jtxApellido.setText(huesped.getApellido() + "");
        jtxCedula.setText(huesped.getCedula() + "");
        jtxDireccion.setText(huesped.getDireccion() + "");
        jtxNombre.setText(huesped.getNombre() + "");
        jtxTelefono.setText(huesped.getTelefono() + "");
        jtxCorreo.setText(huesped.getCorreo() + "");

    }

    private void listarHuesped() {
        jTableHuesped.setModel(controlHuesped.listarHuesped());
    }
}
