/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CtlHuesped;
import controlador.CtlRecepcion;
import excepciones.EmpleadoExistenteException;
import excepciones.EmpleadoNoexistenteException;
import excepciones.PersonaNoEncontradaException;
import javax.swing.JOptionPane;
import modelo.Huesped;
import modelo.Recepcionista;

/**
 *
 * @author Jopcion
 */
public class RegistroRecepcionistaVista extends javax.swing.JInternalFrame {

    CtlRecepcion controlRecepcion;
    CtlHuesped controlHuesped;

    public RegistroRecepcionistaVista() {
        initComponents();
        setVisible(true);
        setMaximizable(false);
        setIconifiable(true);
        setClosable(true);
        setResizable(true);
        this.setTitle("RECEPCIONISTA");
        controlRecepcion = new CtlRecepcion();
        controlHuesped = new CtlHuesped();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRecepcionista = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxNombre = new javax.swing.JTextField();
        jtxCodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxApellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxDireccion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxUsuario = new javax.swing.JTextField();
        jtxContrasenia = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRecepcionista = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jpnRecepcionista.setBackground(new java.awt.Color(255, 255, 255));
        jpnRecepcionista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jpnRecepcionista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(238, 112, 82));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Codigo:");
        jpnRecepcionista.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setBackground(new java.awt.Color(238, 112, 82));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");
        jpnRecepcionista.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jtxNombre.setForeground(new java.awt.Color(51, 51, 51));
        jpnRecepcionista.add(jtxNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 142, 27));

        jtxCodigo.setForeground(new java.awt.Color(51, 51, 51));
        jtxCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxCodigoActionPerformed(evt);
            }
        });
        jpnRecepcionista.add(jtxCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, 32));

        jLabel5.setBackground(new java.awt.Color(238, 112, 82));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Apellido:");
        jpnRecepcionista.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jtxApellido.setForeground(new java.awt.Color(51, 51, 51));
        jpnRecepcionista.add(jtxApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 139, 27));

        jLabel7.setBackground(new java.awt.Color(238, 112, 82));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Telefono:");
        jpnRecepcionista.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jtxTelefono.setForeground(new java.awt.Color(51, 51, 51));
        jpnRecepcionista.add(jtxTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 139, 30));

        jLabel8.setBackground(new java.awt.Color(238, 112, 82));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Dirección:");
        jpnRecepcionista.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jtxDireccion.setForeground(new java.awt.Color(51, 51, 51));
        jpnRecepcionista.add(jtxDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 139, 30));

        btnGuardar.setMnemonic('R');
        btnGuardar.setText("REGISTRAR");
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Enter_ON.png"))); // NOI18N
        btnGuardar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Enter_ON.png"))); // NOI18N
        btnGuardar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Enter_ON.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jpnRecepcionista.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 91, 30));

        btnListar.setBackground(new java.awt.Color(255, 255, 255));
        btnListar.setForeground(new java.awt.Color(238, 112, 82));
        btnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Listar.jpg"))); // NOI18N
        btnListar.setBorder(null);
        btnListar.setBorderPainted(false);
        btnListar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        jpnRecepcionista.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 90, 70));

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setForeground(new java.awt.Color(238, 112, 82));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Search_32px.png"))); // NOI18N
        btnBuscar.setBorder(null);
        btnBuscar.setBorderPainted(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jpnRecepcionista.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 91, 70));

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setForeground(new java.awt.Color(238, 112, 82));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Editar02.jpg"))); // NOI18N
        btnEditar.setBorder(null);
        btnEditar.setBorderPainted(false);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jpnRecepcionista.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 90, 70));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Usuario:");
        jpnRecepcionista.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Contraseña:");
        jpnRecepcionista.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));
        jpnRecepcionista.add(jtxUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 140, 30));
        jpnRecepcionista.add(jtxContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 140, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 409, -1, -1));

        jTableRecepcionista.setBackground(new java.awt.Color(0, 255, 255));
        jTableRecepcionista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jTableRecepcionista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRecepcionista);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 390));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("REGISTRO RECEPCIONISTA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addComponent(jLabel4)
                .addContainerGap(384, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpnRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpnRecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxCodigoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (jtxCodigo.getText().isEmpty() || jtxNombre.getText().isEmpty() || jtxApellido.getText().isEmpty() || jtxTelefono.getText().isEmpty()
                || jtxDireccion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Son requeridos los campos", "¡Aviso!", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            int codigo = Integer.parseInt(jtxCodigo.getText());
            String nombre = jtxNombre.getText();
            String apellido = jtxApellido.getText();
            int telefono = Integer.parseInt(jtxTelefono.getText());
            String direccion = jtxDireccion.getText();
            String usuario = jtxUsuario.getText();
            String contrasenia = jtxContrasenia.getText();
            try {
                Huesped huesped = controlHuesped.buscarHuesped(codigo);
                if (huesped == null) {
                    Recepcionista recepcion = new Recepcionista(codigo, nombre, apellido, telefono, direccion, usuario, contrasenia);
                    controlRecepcion.guardarRecepcionista(recepcion);
                    JOptionPane.showMessageDialog(this, "Se hizo el registro correctamente");
                    refrescar();
                } {
                    JOptionPane.showMessageDialog(this, "No se pude agregar un Huesped como Recepcionista", "¡AVISO!", JOptionPane.ERROR_MESSAGE);
                }
            } catch (EmpleadoExistenteException | EmpleadoNoexistenteException | PersonaNoEncontradaException e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }

        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        try {
            int codigo = Integer.parseInt(jtxCodigo.getText());
            Recepcionista buscar = controlRecepcion.buscarRecepcionista(codigo);
            if (codigo == buscar.getCodigo()) {
                cargarDatos(buscar);
                jtxCodigo.setEnabled(false);
            }
        } catch (EmpleadoNoexistenteException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if (jtxCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "La identificacion por favor", "¡Aviso!", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            int codigo = Integer.parseInt(jtxCodigo.getText());
            String nombre = jtxNombre.getText();
            String apellido = jtxApellido.getText();
            int telefono = Integer.parseInt(jtxTelefono.getText());
            String direccion = jtxDireccion.getText();
            String usuario = jtxUsuario.getText();
            String contrasenia = jtxContrasenia.getText();
            try {
                Recepcionista recepcion = new Recepcionista(codigo, nombre, apellido, telefono, direccion, usuario, contrasenia);
                controlRecepcion.modificarRecepcionista(recepcion);
                JOptionPane.showMessageDialog(this, "Se modifico el registro " + codigo);
                refrescar();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        listarRecepcion();
    }//GEN-LAST:event_btnListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroRecepcionistaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroRecepcionistaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroRecepcionistaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroRecepcionistaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroRecepcionistaVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRecepcionista;
    private javax.swing.JPanel jpnRecepcionista;
    private javax.swing.JTextField jtxApellido;
    private javax.swing.JTextField jtxCodigo;
    private javax.swing.JTextField jtxContrasenia;
    private javax.swing.JTextField jtxDireccion;
    private javax.swing.JTextField jtxNombre;
    private javax.swing.JTextField jtxTelefono;
    private javax.swing.JTextField jtxUsuario;
    // End of variables declaration//GEN-END:variables
  private void refrescar() {
        jtxApellido.setText("");
        jtxCodigo.setText("");
        jtxDireccion.setText("");
        jtxNombre.setText("");
        jtxTelefono.setText("");
        jtxUsuario.setText("");
        jtxContrasenia.setText("");
    }

    private void cargarDatos(Recepcionista r) {
        jtxApellido.setText(r.getApellido() + "");
        jtxCodigo.setText(r.getCodigo() + "");
        jtxDireccion.setText(r.getDireccion() + "");
        jtxNombre.setText(r.getNombre() + "");
        jtxTelefono.setText(r.getTelefono() + "");
        jtxUsuario.setText(r.getUsuario());
        jtxContrasenia.setText(r.getContrasenia());

    }

    private void listarRecepcion() {
        jTableRecepcionista.setModel(controlRecepcion.listarRecepcionista());
    }
}
