/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CtlConfirmarreserva;
import controlador.CtlPedido;
import controlador.CtlRegistroPedidoHuesped;
import controlador.CtlReserva;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;
import modelo.ConfirmarReserva;
import modelo.Factura;
import modelo.Pedido;
import modelo.RegistroPedido;
import modelo.Reserva;

/**
 *
 * @author Jopcion
 */
public class HacerPedidoVista extends javax.swing.JInternalFrame {

    CtlPedido controlPedido;
    Factura factura;
    Pedido pedido;
    ArrayList<Pedido> lista;
    int tpagar;
    CtlRegistroPedidoHuesped controlRegistroPedido;
    private CtlConfirmarreserva controlConfirmarReserva;
    private CtlReserva controlReserva;
    private int cedula;
    private boolean selecciono = false;
    private int idPedido;
    private String nombreProducto;
    private int cantidadProducto;
    private int valorProducto;
    private Reserva active;
    private boolean seleccionoEliminar=false;
    private int idRegistroPedido;
    

    public HacerPedidoVista() {
        initComponents();
        this.setTitle("HACER PEDIDO");
        setVisible(true);
        setMaximizable(false);
        setIconifiable(true);
        setClosable(true);
        setResizable(true);
        controlPedido = new CtlPedido();
        lista = new ArrayList();
        // modelo = new DefaultTableModel();
        listarTabla();
    }

    public HacerPedidoVista(int cedula) {
        initComponents();
        this.setTitle("HACER PEDIDO");
        setVisible(true);
        setMaximizable(false);
        setIconifiable(true);
        setClosable(true);
        setResizable(true);
        controlPedido = new CtlPedido();
        lista = new ArrayList();
        listarTabla();
        this.cedula = cedula;
        controlConfirmarReserva = new CtlConfirmarreserva();
        controlReserva = new CtlReserva();
        controlRegistroPedido = new CtlRegistroPedidoHuesped();
        List<ConfirmarReserva> lista = controlConfirmarReserva.listarConfirmarReservasActivasHuesped(cedula);
        for (ConfirmarReserva confirmarReserva : lista) {
            System.out.println(confirmarReserva.toString());
            active = controlReserva.reservaConfirmada(confirmarReserva.getReservaId());
        }
        listarCarrito(cedula);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProducto = new javax.swing.JTable();
        jlbImagen = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        TxtProducto = new javax.swing.JLabel();
        TxtValorProducto = new javax.swing.JLabel();
        TxtNombreProducto = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCarrito = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(238, 112, 82));
        jLabel4.setText("Productos:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SU PEDIDO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 0, 209, 65));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/HacerPedido.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 11, 44, 43));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Productos:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, -1));

        jTProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTProducto);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 470, 160));
        jPanel2.add(jlbImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 90, 70));

        jLabel7.setText("N° de producto:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel8.setText("Nombre:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel9.setText("Cantidad:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel10.setText("Valor:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        btnComprar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnComprar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito.png"))); // NOI18N
        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        jPanel2.add(btnComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 130, 30));

        TxtProducto.setForeground(new java.awt.Color(0, 102, 255));
        jPanel2.add(TxtProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, 20));

        TxtValorProducto.setForeground(new java.awt.Color(0, 102, 255));
        jPanel2.add(TxtValorProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, 20));

        TxtNombreProducto.setForeground(new java.awt.Color(0, 102, 255));
        jPanel2.add(TxtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 100, 20));
        jPanel2.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 80, -1));

        tableCarrito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableCarritoMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tableCarrito);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 470, 200));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("SU CARRITO");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Multiply_32px.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 130, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 800, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed

        if (selecciono) {
            if (txtCantidad.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "debe ingresar la cantidad que va comprar");
            } else {
                int cantidad = Integer.parseInt(txtCantidad.getText());
                if (cantidad <= cantidadProducto) {
                    try {
                        int total = cantidad * valorProducto;
                        RegistroPedido registroP = new RegistroPedido(nombreProducto, cantidad, valorProducto, total, cedula, active.getHabitacionId());
                        controlRegistroPedido.guardarPedidoHuesped(registroP);
                        controlPedido.modificarStock((cantidadProducto - cantidad), idPedido);
                        listarCarrito(cedula);
                        listarTabla();
                        JOptionPane.showMessageDialog(null, "se agrego correctamente pòr el valor total:" + total);
                        selecciono = false;
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "no se pudo hacer el carrito");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "la cantidad requerida no se encuentra en el inventario debe cambiar la cantidad");
                    txtCantidad.setText("");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "debe seleccionar primero una fila de la tabla producto");
        }
    }//GEN-LAST:event_btnComprarActionPerformed

    private void jTProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTProductoMouseClicked
        // TODO add your handling code here:
        int clic = jTProducto.rowAtPoint(evt.getPoint());
        idPedido = (int) jTProducto.getValueAt(clic, 0);
        nombreProducto = "" + jTProducto.getValueAt(clic, 1);
        cantidadProducto = (int) jTProducto.getValueAt(clic, 2);
        valorProducto = (int) jTProducto.getValueAt(clic, 3);

        TxtProducto.setText(String.valueOf(idPedido));
        TxtNombreProducto.setText(nombreProducto);
        TxtValorProducto.setText(String.valueOf(valorProducto));

        try {
            JLabel lbl = (JLabel) jTProducto.getValueAt(clic, 4);
            jlbImagen.setIcon(lbl.getIcon());
        } catch (Exception e) {
        }
        selecciono = true;
    }//GEN-LAST:event_jTProductoMouseClicked

    private void tableCarritoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCarritoMousePressed
        int row = tableCarrito.getSelectedRow();
        
        if (row > -1) {
            seleccionoEliminar = true;
            idRegistroPedido = (int) tableCarrito.getValueAt(row, 0);
        }
    }//GEN-LAST:event_tableCarritoMousePressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (seleccionoEliminar) {
            if (controlRegistroPedido.eliminar(idRegistroPedido)) {
                JOptionPane.showMessageDialog(this, "exito al eliminar el pedido");
                seleccionoEliminar = false;
                listarCarrito(cedula);
            }else {
                JOptionPane.showMessageDialog(this, "error la elminar el pedido");
            }
        }else{
            JOptionPane.showMessageDialog(this, "debe seleccionar primero una fila de la tabla carrito");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HacerPedidoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HacerPedidoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HacerPedidoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HacerPedidoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HacerPedidoVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TxtNombreProducto;
    private javax.swing.JLabel TxtProducto;
    private javax.swing.JLabel TxtValorProducto;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTProducto;
    private javax.swing.JLabel jlbImagen;
    private javax.swing.JTable tableCarrito;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables

    private void listarTabla() {
        controlPedido.listarPedido(jTProducto);
    }

    private void listarCarrito(int huespedId) {
        tableCarrito.setModel(controlRegistroPedido.listarCarrito(huespedId));
    }
    
    
}
